import type { Metadata } from "next";
import "../styles/styles.scss";

import StyledComponentsRegistry from "../../lib/AntdRegistry";
import AuthProvider from "@/context/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        {/* <AuthProvider> */}
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
